### ISSUE TITLE
请问@sugarat/source-map-cli 是不是需要productionSourceMap：true

### ISSUE THREAD

**Issue by baixjian** [ATQQ/tools#22]
在开启productionSourceMap 的前提下，有没有方式能保证sourcemap只能在内网被访问到，且能正常使用@sugarat/source-map-cli

**Comment by ATQQ** [comment]
构建的时候sourcemap上传到内网的存储上就行我理解 不用和对外的js资源一起放一个存储位置

**Comment by ATQQ** [comment]
可以单独设置sourcemap的 publicPath

**Comment by baixjian** [comment]
> 单独设置sourcemap的 publicPath

感谢大佬回复，还有点疑问，是指vue-cli中的configureWebpack或vite中rollupOptions 自定义sourcemap的储存地址，然后在[此处](https://github.com/ATQQ/tools/blob/main/packages/cli/source-map/src/util/index.ts#L61) 做正确的map文件获取，是吗？

**Comment by ATQQ** [comment]
我记个todo  回头给几个常见构建工具的 demo
