### ISSUE TITLE
feat: 幽灵依赖扫描器建议

### ISSUE THREAD

**Issue by yuzhanglong** [ATQQ/tools#7]
这东西很不错，感谢作者，有一些建议：
1. 支持 monorepo 架构？看了下源码，貌似只支持单个 package.json 校验。
2. 更友好的文件范围控制，可以采用 glob 语法、excludeFiles 选项，让文件匹配更精确一些，过滤一些不必要的搜索。

**Comment by ATQQ** [comment]
建议都很不错，这周末就安排一下

**Comment by ATQQ** [comment]
finish => https://github.com/ATQQ/tools/pull/8

**Comment by yuzhanglong** [comment]
> finish => #8

周一上班试一下，太感谢了！
